services:
  - type: web
    name: scrapergpt-pro-plus
    env: python
    buildCommand: "pip install -r requirements.txt && python -m playwright install"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
